# Generated by Django 4.1 on 2022-10-06 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255)),
                ("slug", models.SlugField()),
                ("video", models.FileField(blank=True, upload_to="")),
                ("description", models.TextField()),
            ],
        ),
    ]
