# Generated by Django 4.1 on 2022-10-20 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("watchtube", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="preview",
            field=models.ImageField(blank=True, upload_to=""),
        ),
    ]
